sudo: false
language: node_js
node_js:
  - "7"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - "meteor npm install"
  - "meteor add dispatch:mocha"

script: "meteor test --once --driver-package dispatch:mocha"
